# logging
logging:
  level:
    org:
      springframework: debug

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  security:
    user:
      name: "sa"
      password: "s3cr3t"
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testDB"
  jpa:
    defer-datasource-initialization: true
    show-sql: true